name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Rename Build
      run: ren ./target/release/json-log-formatter.exe jlf.exe
    - name: Save Build
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "Windows_x64"
        path: "./target/release/jlf.exe"
      
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Rename Build
      run: |
        mv ./target/release/json-log-formatter ./target/release/jlf
        chmod +x ./target/release/jlf
    - name: Save Build
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "MacOS_x64"
        path: "./target/release/jlf"
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
    - name: Rename Build
      run: |
        mv ./target/release/json-log-formatter ./target/release/jlf
        chmod +x ./target/release/jlf
    - name: Save Build
      uses: actions/upload-artifact@v2.3.1
      with:
        name: "Linux_x64"
        path: "./target/release/jlf"
